yousra nodejs Week2
HackYourAssignment/Node.js-Cohort48 pull request #22
Opened 2024-07-09 20:56 UTC by YousraElmag

2024-07-12 22:50 UTC, dardecena requested changes
Please read over comments and make the suggested changes. It is good to understand why it's important to keep API keys secret, and how to keep them secret. 

This is a good learning exercise to understand what to do when sensitive information is exposed and how to recover from it.

2024-07-12 22:50 UTC, dardecena commented on homework/config-files/HackYourTemperature/sources/keys.js
> +export default API_KEY
This is not acceptable, as your API KEY is now compromised. Please get new API key credentials, update your keys.js file, and add  the keys.js file to your .gitignore.

2024-07-12 22:50 UTC, dardecena commented on homework/config-files/HackYourTemperature/app.js
> +});
Good use of try/catch, and using the different http status codes, and informative messages.

2024-07-13 07:10 UTC, YousraElmag commented
thanks for your reviews i add  keys  to gitignore

2024-07-15 18:08 UTC, dardecena approved these changes
Thanks for making the changes. Looks good!

2024-07-15 18:08 UTC, dardecena commented on homework/config-files/HackYourTemperature/.gitignore
Good job!

2024-07-15 18:12 UTC, YousraElmag commented on homework/config-files/HackYourTemperature/.gitignore
thanks

2024-11-29 09:20 UTC, closed without merging